# The URL the site will be built for
base_url = "https://iol2024.org"

title = "IOL 2024"
description = "The official IOL 2024 website"
default_language = "en"

theme = "juice"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
juice_logo_name = "IOL's Teachers Event"
juice_logo_path = "logo-header-sol.svg"
juice_extra_menu = [
    { title = "Main website", link = "https://iol2024.org"}
]
